---
- name: "Deployment application"
  
  vars:
    application_name: 'my_application'
    SECRET_KEY_BASE: 'secretkey'
    RAILS_ENV: 'production'
    RAILS_LOG_TO_STDOUT: 1
    DB_HOST: 127.0.0.1
    DB_PORT: 5432
    DB_USER: 'dbuser'
    DB_PASSWORD: 'dbpassword'
    DB_NAME: 'application'

  hosts: "application_host"
  become: true
   
  pre_tasks:
  - name: "Install new ca-certificates package"
    ansible.builtin.yum:
      name: ca-certificates 
      state: latest
  
  roles:
    - geerlingguy.repo-epel
    - geerlingguy.repo-remi
    - postgresql
    - nginxinc.nginx
    - { role: rvm.ruby,
        tags: ruby,
        rvm1_rubies: ['ruby-2.4.2'],
        rvm1_install_flags: '--auto-dotfiles',
        rvm1_install_path: /usr/local/rvm,
        rvm1_user: root,
        rvm1_gpg_key_server: 'hkp://keyserver.ubuntu.com'
      }
    - deploy_app 
 
  tasks:
  - name: "Reload nginx service"
    service:
      name: nginx
      state: reloaded
