
# Install PostgreSQL:
- name: 'Install PostgreSQL:'
  become: true
  ansible.builtin.yum:
    name: '{{ postgres_dependencies }}'
    state: 'present'  

- name: 'Check if folder is empty'
  become: true
  ansible.builtin.find:
      paths: '/var/lib/pgsql/data/'
      file_type: directory
      hidden: true
      recurse: true
  register: find_out

- name: 'Optionally initialize the database:'
  become_user: postgres
  ansible.builtin.shell:
    cmd: '{{ item }}'
  with_items: 
    - 'postgresql-setup initdb'
  when: 
    - 'find_out.matched == 0'
